# Generated by Django 5.1.5 on 2025-02-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="carousel/")),
                ("link", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "캐러셀",
                "verbose_name_plural": "캐러셀",
                "db_table": "carousel",
            },
        ),
    ]
