# Generated by Django 5.1.5 on 2025-02-12 10:14

from django.db import migrations, models

import carousel.models


class Migration(migrations.Migration):

    dependencies = [
        ("carousel", "0002_carousel_is_active_carousel_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="carousel",
            name="image",
            field=models.ImageField(
                upload_to=carousel.models.carousel_image_path, verbose_name="이미지"
            ),
        ),
    ]
