version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - ./backend/static:/backend/static
      - ./backend/media:/backend/media
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=database
      - PYTHONUNBUFFERED=1
      - DEBUG=True
    command: >
      sh -c "mkdir -p /backend/media/images &&
             chmod -R 777 /backend/media &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    networks:
      - app-network
    restart: always

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/static:/static
      - ./backend/media:/media
      - ./logs/nginx:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network
    restart: always

  database:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 