version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/backend:latest
    platform: linux/amd64
    volumes:
      - ./backend:/backend
      - static_volume:/backend/static
      - media_volume:/backend/media
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DB_HOST=database
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ${DOCKER_USERNAME}/nginx:latest
    platform: linux/amd64
    ports:
      - "80:80"
    volumes:
      - static_volume:/static
      - media_volume:/media
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - app-network

  database:
    image: postgres:14
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email jungseungwon0113@gmail.com -d slog.my -d www.slog.my --agree-tos --no-eff-email

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  app-network:
    driver: bridge
