-- 스키마 생성
CREATE SCHEMA IF NOT EXISTS public;

-- 권한 설정
ALTER SCHEMA public OWNER TO seungwon;

-- 기본 권한 설정
GRANT ALL ON SCHEMA public TO seungwon;
GRANT ALL ON ALL TABLES IN SCHEMA public TO seungwon;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO seungwon;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO seungwon;

-- 향후 생성될 테이블에 대한 권한 설정
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO seungwon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO seungwon;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO seungwon; 