# Generated by Django 5.1.5 on 2025-01-27 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
