# Generated by Django 5.1.5 on 2025-02-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
