name: Django CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build the Docker images
      run: docker-compose build
      
    - name: Start containers
      run: |
        docker-compose up -d
        sleep 10  # 컨테이너가 완전히 시작될 때까지 대기
        
    - name: Check running containers
      run: docker-compose ps
      
    - name: Check backend logs
      run: docker-compose logs backend
      
    - name: Check database logs
      run: docker-compose logs database
      
    - name: Run migrations
      run: docker-compose exec -T backend poetry run python manage.py migrate
      
    - name: Run Django tests
      run: docker-compose exec -T backend poetry run python manage.py test
      
    - name: Clean up
      if: always()
      run: docker-compose down -v
