name: Django CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: djangoblog
          POSTGRES_USER: djangoblog
          POSTGRES_PASSWORD: djangoblog
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        
    - name: Install Dependencies
      working-directory: ./backend
      run: |
        poetry config virtualenvs.create false
        poetry install --no-root

    - name: Run Django Tests
      working-directory: ./backend
      env:
        DJANGO_SECRET_KEY: django-insecure-test-key
        DB_NAME: djangoblog
        DB_USER: djangoblog
        DB_PASSWORD: djangoblog
        DB_HOST: localhost
        DB_PORT: 5432
      run: |
        # 마이그레이션 실행
        poetry run python manage.py makemigrations
        poetry run python manage.py migrate
        
        # 테스트 실행
        poetry run python manage.py test

    - name: Run Linting
      working-directory: ./backend
      run: |
        poetry run black . --check

  docker-build:
    runs-on: ubuntu-latest
    needs: [backend-test]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Create .env file
      run: |
        echo "DJANGO_SECRET_KEY=django-insecure-test-key" > .env
        echo "DB_NAME=djangoblog" >> .env
        echo "DB_USER=djangoblog" >> .env
        echo "DB_PASSWORD=djangoblog" >> .env
        echo "DB_HOST=database" >> .env
        echo "DB_PORT=5432" >> .env
      
    - name: Build and Test Docker Compose
      env:
        DJANGO_SECRET_KEY: django-insecure-test-key
        DB_NAME: djangoblog
        DB_USER: djangoblog
        DB_PASSWORD: djangoblog
        DB_HOST: database
        DB_PORT: 5432
      run: |
        docker-compose build
        docker-compose up -d
        sleep 10  # 컨테이너 시작 대기
        
        # 컨테이너 상태 확인
        docker-compose ps
        docker-compose logs backend
        docker-compose logs database
        
        # 테스트
        docker-compose exec -T backend poetry run python manage.py migrate
        docker-compose exec -T backend poetry run python manage.py test
        
    - name: Clean up
      if: always()
      run: docker-compose down -v
